Repository m0hit-kumar/Bring-The-Menu, pull requests merged in 2023-08, with the labels that each got.

#56 #31 issue solved
  issues_assignees.md
Labels: documentation, good first issue, gssoc23, Level1

#90 added app icon
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile
  ios/Runner/Assets.xcassets/AppIcon.appiconset/100.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/1024.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/114.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/120.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/144.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/152.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/167.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/180.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/20.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/29.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/40.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/50.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/57.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/58.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/60.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/72.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/76.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/80.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/87.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  macos/Flutter/Flutter-Debug.xcconfig
  macos/Flutter/Flutter-Release.xcconfig
  macos/Podfile
  pubspec.lock
Labels: enhancement, good first issue, UI/UX, gssoc23, improvements, Level1

#92 Added introslider and onboarding for new users
  assets/images/rev1.png
  assets/images/rev2.png
  assets/images/rev3.png
  assets/images/rev4.png
  lib/introslider/introslider.dart
  lib/main.dart
  lib/views/admin/dashboard/admin_dashboard.dart
  pubspec.yaml
Labels: gssoc23, Level2

#100 User's Location fetched using GPS
  android/app/src/main/AndroidManifest.xml
  lib/controller/database_controller.dart
  lib/views/admin/complete_profile/complete_profile.dart
  pubspec.yaml
Labels: enhancement, good first issue, gssoc23, Level2
